from pathlib import Path
import json,hashlib,re,subprocess,datetime
base=Path('/tmp/world-iter217-executor');repo=Path.cwd();out=repo/'design_docs/verification/world-iter217/executor-evidence';out.mkdir(exist_ok=True)
sha=lambda b:hashlib.sha256(b).hexdigest()
def read(name):return json.loads((base/name).read_text())
# Preserve the cleared contract and make the current completion scope explicit.
p=repo/'design_docs/planned/w-mcp-dispatch-projection.md';s=p.read_text();s=s.replace('- [ ] Fresh full quorum cleared; unchecked direction freezes resolved.','- [x] Controller planning clearance through the recorded R4 narrow-refinement disposition; original REJECT verdicts preserved.').replace('- [ ] All ACs, RED→GREEN mutations and full verify gates pass (`./scripts/verify_ail.sh`, Go build/tests, required CI).','- [x] Five implementation milestones and executor scoped checks complete; all 43 mapped mutants measured and restored.\n- [ ] Controller final unchanged normal AIL→Go profiles, independent product evaluator, required remote CI and product acceptance.').replace('- [ ] Actual pinned daemon dependency closure measured; proxy/sumdb remain 200.','- [x] Actual pinned daemon dependency closure measured: only hostcall/mcphttp added; proxy/sumdb freshly measured 200 at execution and handoff.').replace('- [ ] Runbook updated with encoded names, version header, non-atomic batch and retry recovery.','- [x] Runbook updated; MCP payloads executed verbatim on a real ephemeral daemon with pinned interpreter and journal evidence.');s+='\n**Executor completion scope (iteration217):** implementation is complete locally. Focused pristine, race (including sequential production clock legs and late-body residual), vet and executable examples pass. The normal unchanged full profiles, independent product judge and required remote CI remain controller-owned and pending; row108/product acceptance is not asserted. See [executor evidence](../verification/world-iter217/executor-evidence/README.md).\n';p.write_text(s)
# Final actual import identity delta.
before=set((base/'closure-before.log').read_text().splitlines());after={x for x in (base/'closure-final.log').read_text().splitlines() if '.' in x.split('/')[0] and not x.startswith('vendor/')};delta={'before':len(before),'after':len(after),'added':sorted(after-before),'removed':sorted(before-after)};assert delta['added']==['github.com/sunholo-data/ailang/serveapi/protocol/hostcall','github.com/sunholo-data/ailang/serveapi/protocol/mcphttp'] and not delta['removed'];(base/'closure-final-delta.json').write_text(json.dumps(delta,indent=2)+'\n')
(base/'final-fetchability.json').write_text(json.dumps({'proxy_status':200,'sumdb_status':200,'observed_utc':'2026-10-01T20:53Z','note':'Both curl --max-time20 commands returned exit0/status200; response bodies banked.'},indent=2)+'\n')
planpath=repo/'design_docs/verification/world-iter217/sprint_w-mcp-dispatch-projection-tranche-a.json';plan=json.loads(planpath.read_text());rows=[]
for row in plan['mutation_inventory']:
 name=row['id'];suffix='';restored='-restored';fence='-fence';proof='-hash'
 if name in ('MUT-ABSENT-PRECHECK-CATCHALL','MUT-ABSENCE-STRING-MATCH','MUT-MAP-NO-LEN-GUARD'):suffix='-mcp';restored='-mcp-restored';fence='-mcp-fence';proof='-mcp-hash'
 elif name=='MUT-TASK-PER-POST':suffix='-current';restored='-current-restored';fence='-current-fence';proof='-current-hash'
 elif name in ('MUT-AGGREGATE-REMOVED','MUT-AGGREGATE-PER-ITEM'):suffix='-accounting';restored='-accounting-restored';fence='-accounting-fence';proof='-accounting-hash'
 applied=read(name+suffix+'.json');rev=read(name+restored+'.json');assert applied['rc']==1 and rev['rc']==0,(name,applied,rev)
 raw=(base/(name+suffix+'.log')).read_text();failed=re.findall(r'^\s*--- FAIL: (\S+)',raw,re.M)
 kind='expected old-pin build/setup refusal' if name=='MUT-PIN-REGRESS' else ('compiled test-only observable guard calibration' if name in ('MUT-BATCH-AS-SINGLE','MUT-BATCH-PARTIAL','MUT-PLAIN-JSON') else 'compiled production mutation')
 if name!='MUT-PIN-REGRESS':assert failed,(name,'no named runtime failure');assert read(name+fence+'.json')['rc']==0,(name,'compile fence')
 proofdata=read(name+proof+'.json');broad=[]
 for candidate in [name+'-mcp-hash.json',name+'-hash.json']:
  data=read(candidate) if (base/candidate).exists() else {}
  if data.get('broad_failed_tests'):broad.append({'proof':candidate,'scope':data.get('broad_scope','whole package in C batch'),'failed_tests':data['broad_failed_tests']})
 result={'id':name,'planner_stage':row['stage'],'kind':kind,'applied_rc':1,'restored_rc':0,'compile_fence_rc':None if name=='MUT-PIN-REGRESS' else 0,'selected_command':applied['cmd'],'selected_failed_tests':failed,'selected_proof':name+proof+'.json','selected_log':name+suffix+'.log','restored_log':name+restored+'.log','actual_broad_executions':broad,'source_hashes':proofdata,'note':'D has no production behavior diff; D-time production mutations exercise C/B behavior, not D-own production nonvacuity.'}
 rows.append(result);row['applied_rc']=1;row['reverted_rc']=0;row['evidence_manifest']='executor-evidence/mutation-manifest.json';row['evidence_kind']=kind
assert len(rows)==43
manifest={'inventory_count':43,'compiled_runtime_kills':42,'expected_dependency_build_refusals':1,'model_transport':'Native Agent codex:gpt-6.1-sol, provider-pin substitution FLAG as controller declared','agent_token_usage':None,'token_note':'Native Agent token metrics unavailable to executor; unknown, not zero.','normal_full_profiles':'controller-owned pending; no goindex diagnostic substitution','records':rows}
(base/'mutation-manifest.json').write_text(json.dumps(manifest,indent=2)+'\n')
plan['status']='implementation_complete_pending_controller_acceptance';plan['implementation_complete']=True;plan['row108_complete']=False;plan['clause6_complete']=False;plan['current_design_sha256']=sha(p.read_bytes());plan['design_hash_note']='design_sha256 retains authorized snapshot provenance. Current hash also includes controller V15 timeout transcription correction and authorized completion-status metadata; no acceptance contract change.';plan['mutation_summary']={'measured':43,'runtime_kills':42,'old_pin_build_refusal':1,'manifest':'executor-evidence/mutation-manifest.json'}
for feature in plan['features']:
 if feature['id']=='M108C_ADAPTERS':feature.update({'passes':True,'completed':'2026-10-01T20:06:19Z','commit':'cad657c51632ebb8d7c64a7ee9601a6075e8c059','notes':'Local adapter controls and 14 C runtime mutants, selected+whole packages, race/vet passed. Controller independent NOREADMIT corroboration complete. Allowlist mutant executed B; five C-assigned dependency/aggregate/wire controls completed during D. Final normal full profile and acceptance remain controller-owned.'})
 elif feature['id']=='M108D_CONFORMANCE':feature.update({'passes':None,'local_checks_passed':True,'started':'2026-10-01T20:06:19Z','completed':'2026-10-01T20:55Z','notes':'Local conformance/tests/docs complete, generated upstream golden, real production clock legs, stage/receipt accounting before timing, late-body residual, exact per-POST lazy cache kill, verbatim payloads and examples, focused pristine/race/vet pass. D production behavior diff empty; mutations cover B/C. Normal final AIL→Go, controller independent D proof, evaluator, required CI/product acceptance remain pending.'})
plan['executor_checks']={name:read(name+'.json') for name in ['d-final-focused','d-final-race','d-final-vet','d-final-examples','closure-final']};planpath.write_text(json.dumps(plan,indent=2)+'\n')
# Bank only text artifacts, never generated Go drafts/caches/binaries.
allowed={'.json','.log','.py','.stdout','.txt'};files=[]
for source in base.rglob('*'):
 if not source.is_file() or source.suffix not in allowed or 'go-cache' in source.parts:continue
 rel=source.relative_to(base);data=source.read_bytes();data.decode('utf-8');assert b'\x00' not in data,source
 target=out/rel;target.parent.mkdir(parents=True,exist_ok=True);target.write_bytes(data);assert target.read_bytes()==data;files.append({'path':str(rel),'sha256':sha(data),'bytes':len(data)})
(out/'raw-file-manifest.json').write_text(json.dumps(files,indent=2)+'\n')
(out/'README.md').write_text('''# Executor evidence — iteration217 row108

Implementation is complete locally. Product acceptance remains pending controller normal unchanged AIL→Go profiles, independent product judge and required CI. No combined quorum PASS is invented; original REJECT verdicts and the recorded narrow-refinement planning disposition remain preserved.

`mutation-manifest.json` maps all 43 rows to actual selected failures, compile fences, byte-restored controls and measured broad red sets. Forty-two runtime mutants compiled; the old module pin is an expected dependency build refusal. Facade import compiled and the actual dependency gate named forbidden `serveapi`. Tests never treat a process timeout as a semantic kill. A1/B earlier controls are focused unless a separately measured broad execution is explicitly listed. C has actual whole-package mutant runs. D initially scoped MCP runs are distinct from later `-whole-package` runs; their red sets are not inferred. No D production behavior diff exists: D-time production mutations cover B/C, while batch/version/SSE decorators are explicitly test-only observable guard calibrations.

Definitive task mutation is a lazy task cache in the context of ONE POST; `-current` evidence uses final task-capture tests. The wider historical per-handler cache and aggregate extensions are additional calibrations in `d-calibrations`, not exact named removal/per-POST proofs. Exact aggregate proofs replace WithTimeout with WithCancel; `-accounting` evidence records N/K/J/admission/commit and fresh receipt checks BEFORE the timing assertion. Wrapper write times are write attempts; delivered baseline HTTP200 bodies corroborate successful writes, while mutant socket failures are not successful writes.

`c-phase1` broad reds include a known fixture baseline failure and are uncredited for broad mutation attribution. The failed batch extension setup is preserved in `d-setup-failure` and uncredited; its later reached-invocation retry is separate. Invalid timeout spelling, script syntax failure, compile/fixture failures and externally capped cache/build waits are retained as instrumentation or failed runs, never credited as semantic kills. No unique cache/filesystem delay cause is asserted. The isolated task cache experiment did not repair the issue and did not remove/reset shared cache. Later C/D focused controls explicitly use GODEBUG=goindex=0; this is a diagnostic environment axis and does not substitute for the controller's normal unchanged full profile.

Production stays credential3/read10/aggregate20/write30 seconds, shared callback20 seconds/eight slots, separate process reservations eight. Both real daemon production legs run sequentially; the batch commits item1, enters/cancels item2 and never enters item3. A separate real slow-body socket closes near30 seconds without success bytes or commit. Positive follow-up work demonstrates cooperative slot release. All new tests ran with loopback and pinned AILANG_BIN v0.41.0. The SSE golden was generated from the actual released v0.47.2 upstream seam. `d-pristine-full` is the actual earlier whole changed-package baseline; `d-final-focused` and `d-final-race` include later strengthened controls. `d-final-vet`, `d-final-examples`, final closure and proxy/sumdb bodies are banked. The guide's three MCP payloads ran verbatim on one mounted ephemeral daemon with a real checked/published pinned-interpreter echo and journal entries1–3; raw SSE and journal hashes are in those logs.

Source proof hashes describe the measured snapshot and byte restoration, not falsely every later HEAD. C projection comment metadata changed after early mutation snapshots; current controller C corroboration covers the landed source. Original design hash is authorized snapshot provenance; sprint JSON separately records current completion-metadata hash. Native Agent token usage is unknown, not zero. Raw text file hashes/byte counts are in `raw-file-manifest.json`. Controller root-stage files are separate and are not staged by this executor.
''')
print(json.dumps({'banked_text_files':len(files),'mutation_rows':len(rows),'current_design_sha256':plan['current_design_sha256'],'closure_delta':delta}))
