#!/usr/bin/env bash
# Reproduces the load-bearing empirical claims (V-rows) of w-m1-ailang-hardening against the
# PINNED released AILANG v0.30.0 + Z3 4.16.0. Fixtures are committed as fixtures/*.ail.txt so the
# CI gate (scripts/verify_ail.sh, which sweeps *.ail under design_docs/) does NOT pick them up —
# some are DESIGNED to fail (encoder error / counterexample). This script copies each fixture to a
# temp dir as .ail, runs the pinned binary, and records exit codes + JSON so the design doc's
# claims are auditable and re-runnable.
#
# Usage:  AILANG_BIN=/tmp/ailang-v0300/ailang ./run.sh   (default AILANG_BIN shown below)
# Writes: OUTPUTS.md (committed alongside this script).
set -uo pipefail
HERE="$(cd "$(dirname "$0")" && pwd)"
AILANG_BIN="${AILANG_BIN:-/tmp/ailang-v0300/ailang}"
WORK="$(mktemp -d)"
OUT="$HERE/OUTPUTS.md"

hr() { printf '\n---\n\n'; }
run_check() { # name file expect_exit
  local name="$1" f="$2"
  cp "$HERE/fixtures/$f" "$WORK/${f%.txt}"          # e.g. verified_baseline.ail.txt -> verified_baseline.ail
  echo "### $name — \`ai-check ${f%.txt}\`"
  local json rc
  json="$( "$AILANG_BIN" ai-check "$WORK/${f%.txt}" 2>&1 )"; rc=$?
  echo "exit code: \`$rc\`"
  echo '```json'
  echo "$json"
  echo '```'
  hr
}
run_test() { # name file
  local name="$1" f="$2"
  cp "$HERE/fixtures/$f" "$WORK/${f%.txt}"
  echo "### $name — \`test --format json ${f%.txt}\`"
  local json rc
  json="$( "$AILANG_BIN" test --format json "$WORK/${f%.txt}" 2>&1 )"; rc=$?
  echo "exit code: \`$rc\`"
  echo '```json'
  echo "$json"
  echo '```'
  hr
}

{
  echo "# w-m1-ailang-hardening — verification OUTPUTS (auto-generated by run.sh)"
  echo
  echo "- **Binary**: \`$AILANG_BIN\` — \`$("$AILANG_BIN" --version 2>&1 | tr '\n' ' ')\`"
  echo "- **Binary sha256**: \`$(shasum -a 256 "$AILANG_BIN" 2>/dev/null | awk '{print $1}')\`"
  echo "- **Repo commit**: \`$(git -C "$HERE" rev-parse --short HEAD 2>/dev/null)\`"
  echo "- **Generated on**: (stamp added at commit time — Date.now() unavailable in-harness)"
  hr
  echo "## Claim reproductions"
  hr
  run_check "verified_baseline (V1/V2/V5/V9/V17): expect exit 0, verify.verified==6, no \`commit\` entry, BARE identity names" verified_baseline.ail.txt
  run_check "encoder_limits (V3/V8/V10-silent): expect EXIT 0 despite verify.errors>=1 (SILENT error class)" encoder_limits.ail.txt
  run_check "counterexample (V10): expect EXIT 1, verify.counterexample>=1" counterexample.ail.txt
  run_test  "inline_tests (V12/V18): expect exit 0, failed_tests==0, passed_tests==6, tests[].name == <fn>_test_<N>" inline_tests.ail.txt
} > "$OUT"

rm -rf "$WORK"
echo "wrote $OUT"
